### ISSUE TITLE
2.0a1 Meta

### ISSUE THREAD

**Issue by rpkilby** [rpkilby/django-filter#6]
- [x] The `suffixed-multiwidget-default` branch contains the changes to make `SuffixedMultiWidget` the default.   refs PR 681, although the branch was rebased on top of the isort PR.
- [x] Rename `Filter.name` to `Filter.field_name` to better indicate that it refers to the model field name, and not the attribute name of the filter on the filterset.
- [x] Rework `.qs` API, deprecate filterset strictness
- [x] Deprecate `Meta.together`? Recommend Form class override instead.
- [x] Drop python 2.x support?
- [x] Fixup method signagures (branch: improve-method-sig)
- [x] Fix validation error codes

**Comment by rpkilby** [comment]
Hey @carltongibson. btw, here are some of my plans for a 2.x release.

**Comment by carltongibson** [comment]
* [x] Drop Python 2 support ? 😃

**Comment by rpkilby** [comment]
My body is ready.

**Comment by rpkilby** [comment]
But on a serious tack, I'd like to release 2.x shortly after 1.1, as it affects the work I'm doing on drf-filters (which solves the to-many query issue)

**Comment by rpkilby** [comment]
What were you thinking?

**Comment by carltongibson** [comment]
If "shortly" means ≈December then yes, why not?

**Comment by rpkilby** [comment]
What if shortly were to mean the same day as 1.1

**Comment by rpkilby** [comment]
It's just a "what if", but what if...

**Comment by carltongibson** [comment]
Erm, well, it's docs really. 

The changes we've discussed are OK. We could get them in. You'd then be free to develop against that. 

The thing with a release is that a number like 2.0 gets people to look, so I don't want to waste that having not made the docs better (which has been a Long Term goal)

**Comment by carltongibson** [comment]
If you like I could publish a `2.0a1`?, then you could `pip install --pre ...`

**Comment by rpkilby** [comment]
An alpha release would be a good idea. It's been on my longtime todo list to update the docs (there were some great talks at PyCon in regards to this).

**Comment by rpkilby** [comment]
Also, how do you feel about renaming `Filter.name` to `Filter.field_name`. I'm simultaneously for and against it. 

The documentation can be confusing, since the "filter name" can refer to the filter's *attribute* name on the Filterset, but it could also refer to the filter's `.name` attribute, which is supposed to refer to the model field name. There have been quite a few cases where `Filter.name` has been improperly used. eg, `CharFilter(name='field__lte')` instead of `CharFilter(name='field', lookup_expr='lte')`.

**Comment by rpkilby** [comment]
My case for `Filter.name` is that it's terse, and this could possibly be improved through concise documentation.

**Comment by carltongibson** [comment]
I think I'm +1 there. (For the change I mean) 

The other case that always comes up is "how do I give my QS parameter a better name than `model__other_model__other_other_model__attribute`?" This would be eased with a better name (and docs yes) 

Maybe `target` — mirroring DRF's `source`...?

**Comment by rpkilby** [comment]
I see three candidates:
- `field_name` - independent of DRF terminology, semi-terse. I *very slightly* preference this.
- `source` - aligns with DRF terminology, is terse. 
- `target` - is an option, but seems inferior to `source`, given the former's alignment to DRF terminology.

I think `source` or `field_name` are both good calls. The importance is the differentiation from it's attribute name on the `FilterSet`. It's your call. 

The main benefit for me is improving the clarity of docs/SO questions.

We could also just leave it be and defer to a later date.

**Comment by carltongibson** [comment]
Go `field_name`. 👍

**Comment by rpkilby** [comment]
Hi @carltongibson, so what are your thoughts on zeroing in on a 2.x alpha release? At this point, I think all of the PRs are in a good state. They should all be tested and just need to be reviewed.

Part of my motivation here is that I'm trying to push out djangorestframework-filters 1.0, and am targeting django-filter 2.x, given the planned changes to validation and filtering. For now, I've created a 2.x-alpha branch on my fork, which has all of these changes merged in. So far, everything looks good.

Here's what I'm thinking in terms of a game plan:

- Review/merge PR's
- Release 2.0.0-alpha.1
- Update docs (some thoughts in #2)
- Maybe churn on more alphas?
- ...
- Eventually release 2.0

----

More specifically, here are my thoughts on the open PRs:

The following are fairly straightforward and just need a once over.
- `https://github.com/carltongibson/django-filter/pull/770` - Update widgets to use suffixes
- `https://github.com/carltongibson/django-filter/pull/797` - Drop python 2, Django<1.11 support
- `https://github.com/carltongibson/django-filter/pull/801` - Remove more deprecations

I'm +1 on the following, but it covers a couple different areas and probably needs closer review.
- `https://github.com/carltongibson/django-filter/pull/803` - Fix Schema warnings

I'm +0.5 on the following, I think the reordered arguments are better. The question is on whether we should use keyword only arguments. 
- `https://github.com/carltongibson/django-filter/pull/800` - Method signature improvements

I'm +1 on this, but it should probably be merged last, as it will most likely need to be rebased and touches a large portion of the package. Unfortunately, some related changes were dependent on this PR, so they were merged in on top of the base PR (eg, validation error code). That said, I've updated the description w/ 
 a change list and have tried to keep the commit history fairly discrete. 
- `https://github.com/carltongibson/django-filter/pull/788` - Rework validation

**Comment by carltongibson** [comment]
@rpkilby Let's go for it. Lets get these PRs in and then I'll push a 2.0alpha to PyPI. You can develop of that, and I'll potter on the docs over the autumn. 

I don't see a rush here but, I'll look to a 2.0 mid-december.

**Comment by rpkilby** [comment]
@carltongibson, I'm around right now to help rebase, and push this out. I'm also more than happy to contribute to the docs, but my primary focus is djangorestframework-filters 1.x

**Comment by carltongibson** [comment]
OK. Lets' get them in now then... 😀

I appreciate your input here. I'm really happy to take on the docs rewrite: I've been mulling it over for a long time now. (Obviously happy for input, but if you want to work on `djangorestframework-filters` that's totally cool!)

**Comment by rpkilby** [comment]
🎉

**Comment by carltongibson** [comment]
https://github.com/carltongibson/django-filter/releases/tag/2.0.0.dev1


`pip install --pre django-filter`

**Comment by rpkilby** [comment]
It's amazing that the last ~6 months have converged so quickly. Feels good, man. 😄

**Comment by carltongibson** [comment]
Yeah it’s nice. Well done on all your efforts! Awesome stuff.
